version: "3.1"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"

# adminer is a simple frontend for you to interact with the database
  adminer:
    image: adminer
    ports:
      - 8080:8080