version: "3.1"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: joinme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

# adminer is a simple frontend for you to interact with the database
  adminer:
    image: adminer
    ports:
      - 8081:8081