import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { cn } from '@/lib/utils';
import { UserProvider } from '@/context/user';

const inter = localFont({ 
  src: "./PixelifySans.ttf"
})

export const metadata: Metadata = {
  title: 'Messenger',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-black select-none")}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  )
}