import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'

const noto = Noto_Sans({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
  variable: "--noto-sans",
});

export const metadata: Metadata = {
  title: "Joinme",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={noto.className}>
        {children}
      </body>
    </html>
  )
}
